name: Validate quickstarts

on:
  workflow_run:
    workflows: ["Validation Gate"]
    types:
      - completed

jobs:
  print:
    name: hello
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2

  ensure-schema-compliance:
    name: Ensure schema compliance
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: validation_gate.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Get PR number
        id: get_pr_number
        run: |
          export PR_NUMBER=$(cat artifact/pr_number.txt)
          echo "::set-output name=pr-number::$PR_NUMBER"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ steps.get_pr_number.outputs.pr-number }}/merge'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Validate pr quickstart files
        id: testing_me
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NR_API_URL: "https://api.newrelic.com/graphql"
          NR_API_TOKEN: ${{ secrets.NR_API_TOKEN }}
        run: |
          echo "Hello world"
      
      - name: Add commit status
        if: always()
        run: |
          export COMMIT_SHA=$(echo '${{ toJSON(github.event) }}' | jq '.workflow_run.head_commit.id' | tr -d '"')
          curl \
            -X POST \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/$COMMIT_SHA \
            -d '
            {
              "description": "Validate install plans 2", 
              "state": "${{ steps.testing_me.outcome }}", 
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "context": "Validation 2"
            }'

  ensure-quickstart-names-ids-are-unique:
    name: Ensure quickstart names and ids are unique
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: validation_gate.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Get PR number
        id: get_pr_number
        run: |
          export PR_NUMBER=$(cat artifact/pr_number.txt)
          echo "::set-output name=pr-number::$PR_NUMBER"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ steps.get_pr_number.outputs.pr-number }}/merge'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Check for unique names and ids
        id: testing_me
        run: |
          exit 1

      - name: Add commit status
        if: always()
        run: |
          export COMMIT_SHA=$(echo '${{ toJSON(github.event) }}' | jq '.workflow_run.head_commit.id' | tr -d '"')
          curl \
            -X POST \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/$COMMIT_SHA \
            -d '
            {
              "description": "Validate install plans 1", 
              "state": "${{ steps.testing_me.outcome }}", 
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "context": "Validation 1"
            }'