name: Validate install plans

on:
  workflow_run:
    workflows: ["Validation Gate"]
    types:
      - completed

jobs:
  validate-install-plan-schema:
    name: Validate install plan schema
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: validation_gate.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Get PR number
        id: get_pr_number
        run: |
          export PR_NUMBER=$(cat artifact/pr_number.txt)
          echo "::set-output name=pr-number::$PR_NUMBER"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ steps.get_pr_number.outputs.pr-number }}/merge'

      - name: Validate new files
        id: validate_install_plans
        run: |
          exit 0

      - name: Add commit status
        run: | 
          export COMMIT_SHA=$(echo '${{ toJSON(github.event) }}' | jq '.workflow_run.head_commit.id' | tr -d '"')
          curl \
            -X POST \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/$COMMIT_SHA \
            -d '
            {
              "description": "Validate install plans 3", 
              "state": "${{ steps.validate_install_plans.outcome }}", 
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "context": "Validation 3"
            }'
